Borda pr
mggg/VoteKit pull request #31
Opened 2023-07-20 15:18 UTC by bmacias01

Andrew and I added Borda Election code in the election_types.py file.

2023-07-20 20:26 UTC, jgibson517 commented on src/votekit/election_types.py
> +    def run_borda_election(self):
lets unpack this before we return for clarity

i.e 
```suggestion
    def run_borda_election(self):
        profile, outcome = self.run_borda_step()
        return outcome 
     
    
```

2023-07-21 20:13 UTC, jgibson517 requested changes

2023-07-24 17:33 UTC, andrewmhong commented on src/votekit/election_types.py
> +                    candidate_rank_freq[candidate] = [
Done

2023-07-24 17:33 UTC, andrewmhong commented on src/votekit/election_types.py
> +            index = 0
Done

2023-07-24 17:33 UTC, andrewmhong commented on src/votekit/election_types.py
> +                    candidate_rank_freq[candidate][index] += frequency
Done

2023-07-24 17:33 UTC, andrewmhong commented on src/votekit/election_types.py
> +        for key in candidate_rank_freq:
Done

2023-07-24 17:34 UTC, andrewmhong commented on src/votekit/election_types.py
> +        return PreferenceProfile(ballots=self.profile.get_ballots()), Outcome(
Done

2023-08-01 14:24 UTC, closed without merging