Adding Updated Borda Test
mggg/VoteKit pull request #55
Opened 2023-07-28 14:30 UTC by bmacias01

This Borda Election computes and distributes fractional points for short ballots

2023-07-28 14:33 UTC, bmacias01 commented
Hi James,
Please ignore the previous Borda Pull request. This code is an updated Borda election that distributes fractional points for candidates not elected in short ballots. Test code was also written.

2023-08-03 17:59 UTC, jgibson517 requested changes

2023-08-03 17:59 UTC, jgibson517 commented on src/votekit/election_types.py
> +            if self.standard is True:
what's this boolean doing, if standard is false is some different type of borda scoring supposed to occur

2023-08-03 17:59 UTC, jgibson517 commented on src/votekit/election_types.py
> +def seqRCV_transfer(
Is this for borda?

2023-08-08 16:11 UTC, closed without merging